### ISSUE TITLE
Create a folder by default (proposition)

### ISSUE THREAD

**Issue by editadapt** [daisy/word-save-as-daisy#15]
Conversion generate files at the root of the selected folder so user is obliged to create new folder for each conversion. 

The proposed comportment is that a folder is created at each conversion and named by the FileName of the converted file. 

In case a folder with the same name exist, add a digit to the folder name (FileName1).

**Comment by NPavie** [comment]
Hi !
Thanks for the proposition, i'll look at that for a futur release.

**Comment by NPavie** [comment]
With the switch to DAISY Pipeline 2 and the refactorization of the code, on each conversion, the process is now creating a new folder in the targeted output folder with the following naming scheme to store the conversion result:

`<filename>_<TargetedFormat>_<timestamp>`

Where the timestamp is in format `yyyyMMddHHmmssffff` (see https://learn.microsoft.com/fr-fr/dotnet/standard/base-types/custom-date-and-time-format-strings for description of this format)

For exemple, for an export of a document `test file.docx` to DTBook XML, this will create a folder `test file_DtbookXML_202401301009175599` in the output folder>
