### ISSUE TITLE
About Note conversion

### ISSUE THREAD

**Issue by editadapt** [daisy/word-save-as-daisy#16]
I've tryed the _AddFootnote_ button from _Accessibility_ Tab of word ribbon but i can't make it work. So i use the native word function. Attached is a docx + xml i used for testing.

I'm note sure about the best way to manage notes, but here are some feedback:

## At XML conversion Notes gets a textual number added
- It's a problem if we edit the XML file after conversion and need to add / suppress notes. 
- This numbering starts at 0 (it should start at 1)

A way could be to provide option for note conversion. something like : _numbering_ or _Add a generic character (*)_ or _place link on the related word_.

## Endnotes are not translated
I get a link but loose the content

[Test document for notes.zip](https://github.com/daisy/word-save-as-daisy/files/7863134/Test.document.for.notes.zip)

**Comment by NPavie** [comment]
Endnotes fix included with the new 2.7.2 release.
Notes numbering customization remains to be added.

We might need to discus internaly if it would not be coherent to remove the footnote button in the next updates, as the official way to manage notes is now to use the word native notes, at least for word 2010 and later versions.

**Comment by NPavie** [comment]
Some updates with the latest test 2.8.3 pre-release : 

- Footnotes management buttons have been removed from the addin to solely rely on Word native footnotes functionnalities: aedd09c413181f323d8afdf5600ce598c58d6cfa

- Footnotes export customization is available through the addin settings panel, including footnotes positionning in the exported dtbook and footnotes prefix customization.

I'll close this issue
