### ISSUE TITLE
Labels not found and raising an exception

### ISSUE THREAD

**Issue by NPavie** [daisy/word-save-as-daisy#17]
After the code refactoring, some labels are not found and the UI raises an exception about not finding the resource file.

**Comment by NPavie** [comment]
Fixed in c0caa15f7a0af54bc601d89eb167270ba6d5a166 : 
- The labels file has been changed to be placed under a more common namespace (properties)
- The file has been assigned the correct namespace
- the custom resource manager class now returns the key if it is not found instead of raising an exception

**Comment by bertfrees** [comment]
To be clear, you haven't created a new release, but you just changed the download of v2.7?

**Comment by NPavie** [comment]
Yes, i updated the installer in the release page to provide the patch ASAP (and avoid downloads of the installer with the issue for newer user)

Given the time frame, if we get more reports for this, i'll send back the email with the repaire request.

**Comment by bertfrees** [comment]
OK. I'll change milestone to 2.7.0 then.
