### ISSUE TITLE
Fix log4j vulnerability

### ISSUE THREAD

**Issue by bertfrees** [daisy/word-save-as-daisy#26]
Either

- get rid of the Pipeline 1 dependency, or
- [fix the vulnerability in Pipeline 1](https://github.com/daisy/pipeline1/issues/7).

**Comment by NPavie** [comment]
Daisy pipeline 1 is completely removed from the application starting commit 29aa5256fd8671c6c97f9ca7a0b2be01439ecdb7 after replacing its usage by DAISY Pipeline 2 equivalent scripts in the code (#28 and #27)

Installer is also updated to delete the pipeline-lite-ms folder of previous installation.
