### ISSUE TITLE
Support documents saved in OneDrive

### ISSUE THREAD

**Issue by bertfrees** [daisy/word-save-as-daisy#6]
Reported by Prashant.

There seems to be an issue when converting documents saved in OneDrive. The following error is raised:

> The given path's format is not supported.    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath) 
>    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost) 
>    at DaisyWord2007AddIn.Connect.PrepareForSaveAsDaisy(IPluginEventsHandler eventsHandler, Document activeDocument, String controlId)   at DaisyWord2007AddIn.Connect.SaveAsDaisy(IRibbonControl control)

**Comment by bertfrees** [comment]
@NPavie Can this issue be considered fixed? If yes, let's close this and add it to the next release milestone.

**Comment by NPavie** [comment]
Yes I think it can be.
It will be packaged with the next release
